export const SET_USER_DATA = "SET_USER_DATA";
export const SET_HARDWARE_DATA = "SET_HARDWARE_DATA";
export const SET_SUBSCRIPTION_DATA = "SET_SUBSCRIPTION_DATA";
export const SET_ACTIVE_USER = "SET_ACTIVE_USER";
